[build-system]
build-backend = "setuptools.build_meta"
requires = [ "setuptools>=77", "wheel" ]

[project]
name = "wagtail-review"
version = "0.5"
description = "Review workflow for Wagtail"
readme = "README.md"
license = "BSD-3-Clause"
authors = [
  { name = "Matthew Westcott", email = "matthew.westcott@torchbox.com" },
]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Framework :: Django",
  "Framework :: Django :: 5.2",
  "Framework :: Django :: 6.0",
  "Framework :: Wagtail",
  "Framework :: Wagtail :: 7",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "swapper>=1.4",
  "wagtail>=7",
]
optional-dependencies.testing = [
  "coverage>=6.5",
  "pre-commit>=4",
  "tox>=4.18.1",
]
urls.Changelog = "https://github.com/wagtail-nest/wagtail-review/blob/main/CHANGELOG.md"
urls.Source = "https://github.com/wagtail-nest/wagtail-review"

[tool.setuptools]
package-data.wagtail_review = [
  "static/**/*",
  "templates/**/*",
]
packages.find.include = [ "wagtail_review*" ]

[tool.ruff]
target-version = "py310"
lint.extend-select = [
  "B",      # flake8-bugbear
  "BLE",    # flake8-blind-except
  "C4",     # flake8-comprehensions
  "DJ",     # flake8-django
  "E",      # pycodestyle errors
  "F",      # pyflakes
  "I",      # isort
  "PGH",    # pygrep-hooks
  "PIE",    # flake8-pie
  "RUF100", # unused noqa
  "SIM",    # flake8-simplify
  "T20",    # flake8-print
  "UP",     # pyupgrade
  "W",      # pycodestyle warnings
  "YTT",    # flake8-2020
]
lint.extend-ignore = [
  "E501", # no line length errors
]
lint.fixable = [ "C4", "E", "F", "I", "UP" ]
lint.isort.known-first-party = [ "wagtail_review" ]
